baseURL 				        = "/"
title 					        = "Odyssey Tours"
theme                   = ["odyssey"]
paginate 				        = "50"
summaryLength 			    = "15"
disqusShortname 		    = "" # get your shortname form here : https://disqus.com
defaultContentLanguage 	= "en"
disableKinds 			      = ["RSS"]
googleAnalytics         = "" 
# enableGitInfo         = true
enableRobotsTXT         = true
# canonifyURLs          = true
ignoreErrors            = ["error-output-taxonomy"]

[taxonomies]
  tag                   = "tags"
  category              = "categories"

[params]
env                     = "PUBLIC"
gtm_id                  = "GTM-K4W9GX8"
gtm_datalayer           = "basic"
disallow_search_engines = false 
logo                    = "/logo.gif"
googleMapsAPIKey        = "AIzaSyD7brYWRgjb-1K4vXXGxSPukB1dXxwvK7o"

[params.csp] 
  childsrc = ["'self'"]
  fontsrc = ["'self'"]
  formaction = ["'self'"]
  framesrc = ["'self'"]
  imgsrc = ["'self'"]
  objectsrc = ["'none'"]
  stylesrc = ["'self'"]
  scriptsrc = ["'self'",
    "'unsafe-inline'",
    "https://www.googletagservices.com",
    "cdnjs.cloudflare.com/"]

[outputs]
home                    = ["html"]
page                    = ["html","json"]
section                 = ["html","json"]
taxonomy                = ["html","json"]

[Languages]
  [Languages.en]
    languageName = "English"
    languageCode = "en-gb"
    contentDir = "content/english"
    languageFlag = "🇬🇧"
    weight = 1
    home = "Home"
    unicode = "&#127468;&#127463;"

    [[Languages.en.menu.main]]
    name = "Home"
    identifier = "home"
    pre = "home"
    url = "/"
    weight = 10
  [[Languages.en.menu.main]]
    name = "Tour Ideas"
    identifier = "tour-ideas"
    pre = "pen-tool"
    url = "/tour-ideas/"
    weight = 20
  [[Languages.en.menu.main]]
    name = "Explore"
    identifier = "explore"
    pre = "pen-tool"
    weight = 30  
  [[Languages.en.menu.main]]
    name = "Explore by Region"
    parent = "explore"
    pre = "pen-tool"
    url = "/explore-india/explore-by-region/"
    weight = 31
  [[Languages.en.menu.main]]
    name = "Explore by State"
    parent = "explore"
    pre = "pen-tool"
    url = "/states/"
    weight = 32
  [[Languages.en.menu.main]]
    name = "Explore by City"
    parent = "explore"
    pre = "pen-tool"
    url = "/explore-india/explore-by-city"
    weight = 33
  [[Languages.en.menu.main]]
    name = "Experience"
    identifier = "experience"
    pre = "pen-tool"
    url = "/experience/"
    weight = 40
  [[Languages.en.menu.main]]
    name = "Unique experiences"
    parent = "experience"
    pre = "pen-tool"
    url = "/experience/unique-experiences/"
    weight = 41
  [[Languages.en.menu.main]]
    name = "Explore by Interest"
    parent = "experience"
    pre = "pen-tool"
    url = "/experience/explore-by-interest/"
    weight = 42
  [[Languages.en.menu.main]]
    name = "Hotels"
    identifier = "hotels"
    pre = "bed"
    url = "/special-hotels/"
    weight = 50
  [[Languages.en.menu.main]]
    name = "About Us"
    identifier = "about"
    pre = "bed"
    url = "/about-us/"
    weight = 60
  [[Languages.en.menu.main]]
    name = "Why Us?"
    parent = "about"
    url = "/about-us/why-us/"
    weight = 61
  [[Languages.en.menu.main]]
    name = "Our Team"
    parent = "about"
    url = "/about-us/our-team/"
    weight = 62
  [[Languages.en.menu.main]]
    name = "Sustainable Travel"
    parent = "about"
    url = "/about-us/sustainable-travel/"
    weight = 62
   [[Languages.en.menu.main]]
    name = "FAQ"
    identifier = "faq"
    pre = "bed"
    url = "/faq/"
    weight = 70
   [[Languages.en.menu.main]]
    name = "Contact"
    identifier = "contact"
    pre = "bed"
    url = "/contact/contact-us/"
    weight = 80