baseURL 				= "/"
title 					= "Odyssey Tours"
theme                   = "odyssey"
paginate 				= "50"
summaryLength 			= "15"
disqusShortname 		= "" # get your shortname form here : https://disqus.com
defaultContentLanguage 	= "en"
disableKinds 			= ["RSS"]
googleAnalytics         = "" 
# enableGitInfo         = true
enableRobotsTXT         = true
# canonifyURLs          = true


[taxonomies]
  tag         = "tags"
  category    = "categories"

[params]
env           = "PUBLIC"
gtm_id        = "GTM-K4W9GX8"
gtm_datalayer = "basic"
disallow_search_engines = false 
logo          = "/logo.gif"

[Languages]
  [Languages.en]
    languageName = "English"
    languageCode = "en-gb"
    contentDir = "content/english"
    languageFlag = "🇬🇧"
    weight = 1
    home = "Home"
    unicode = "&#127468;&#127463;"

    [[Languages.en.menu.main]]
    name = "Home"
    identifier = "home"
    pre = "home"
    url = "/"
    weight = 10
  [[Languages.en.menu.main]]
    name = "Tours"
    identifier = "tours"
    pre = "pen-tool"
    url = "/tours/"
    weight = 20
  [[Languages.en.menu.main]]
    name = "States"
    identifier = "states"
    pre = "pen-tool"
    weight = 30  
  [[Languages.en.menu.main]]
    name = "States"
    parent = "states"
    pre = "pen-tool"
    url = "/states/"
    weight = 31
  [[Languages.en.menu.main]]
    name = "Interstates"
    parent = "states"
    pre = "pen-tool"
    url = "/interstates/"
    weight = 32
  [[Languages.en.menu.main]]
    name = "Cities"
    identifier = "cities"
    pre = "pen-tool"
    url = "/tags/#cities-list"
    weight = 40
  [[Languages.en.menu.main]]
    name = "Tags"
    identifier = "tags"
    pre = "tag"
    weight = 50
  [[Languages.en.menu.main]]
    name = "Tags"
    parent = "tags"
    url = "/tags/"
    weight = 51
  [[Languages.en.menu.main]]
    name = "Sitemap"
    parent = "tags"
    url = "/sitemap/"
    weight = 52